-- MySQL Script generated by MySQL Workbench
-- lun. 19 févr. 2018 14:48:28 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema MoOSe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MoOSe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MoOSe` DEFAULT CHARACTER SET latin1 ;
USE `MoOSe` ;

-- -----------------------------------------------------
-- Table `MoOSe`.`application_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MoOSe`.`application_type` (
  `application_type_id` INT(11) NOT NULL AUTO_INCREMENT,
  `application_type_name` VARCHAR(45) NULL DEFAULT NULL,
  `application_type_pattern` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`application_type_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `MoOSe`.`index`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MoOSe`.`index` (
  `index_id` INT(11) NOT NULL AUTO_INCREMENT,
  `index_source` VARCHAR(45) NOT NULL,
  `index_num` INT(11) NOT NULL,
  `index_value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`index_id`),
  UNIQUE INDEX `index_id_UNIQUE` (`index_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `MoOSe`.`platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MoOSe`.`platform` (
  `platform_id` INT(11) NOT NULL AUTO_INCREMENT,
  `platform_name` VARCHAR(255) NOT NULL,
  `platform_path` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`platform_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `MoOSe`.`run`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MoOSe`.`run` (
  `run_id` INT(11) NOT NULL AUTO_INCREMENT,
  `run_name` VARCHAR(45) NOT NULL,
  `run_date` DATE NULL DEFAULT NULL,
  `run_read_length` VARCHAR(45) NULL DEFAULT NULL,
  `run_library_type` VARCHAR(225) NULL DEFAULT NULL,
  `platform_id` INT(11) NOT NULL,
  `run_isvalid` TINYINT(1) NULL DEFAULT NULL,
  `run_adapter_r1` VARCHAR(255) NULL DEFAULT NULL,
  `run_adapter_r2` VARCHAR(255) NULL DEFAULT NULL,
  `run_number_of_samples` INT(11) NULL DEFAULT NULL,
  `run_sample_sheet_isvalid` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`run_id`),
  UNIQUE INDEX `run_name_UNIQUE` (`run_name` ASC),
  INDEX `fk_run_platform_idx` (`platform_id` ASC),
  CONSTRAINT `fk_run_platform`
    FOREIGN KEY (`platform_id`)
    REFERENCES `MoOSe`.`platform` (`platform_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `MoOSe`.`monitoring`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MoOSe`.`monitoring` (
  `monitoring_id` INT(11) NOT NULL AUTO_INCREMENT,
  `monitoring_statut` VARCHAR(225) NULL DEFAULT NULL,
  `monitoring_date` DATETIME NULL DEFAULT NULL,
  `run_id` INT(11) NOT NULL,
  PRIMARY KEY (`monitoring_id`),
  INDEX `fk_monitoring_run1_idx` (`run_id` ASC),
  CONSTRAINT `fk_monitoring_run1`
    FOREIGN KEY (`run_id`)
    REFERENCES `MoOSe`.`run` (`run_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `MoOSe`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MoOSe`.`project` (
  `project_id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(255) NULL DEFAULT NULL,
  `project_bioinfo_name` VARCHAR(255) NULL DEFAULT NULL,
  `project_contact` VARCHAR(255) NULL DEFAULT NULL,
  `project_end_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`project_id`),
  UNIQUE INDEX `project_name_UNIQUE` (`project_name` ASC),
  UNIQUE INDEX `project_bioinfo_id_UNIQUE` (`project_bioinfo_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `MoOSe`.`species`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MoOSe`.`species` (
  `species_id` INT(11) NOT NULL AUTO_INCREMENT,
  `species_name` VARCHAR(255) NOT NULL,
  `species_pattern` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`species_id`),
  UNIQUE INDEX `species_name_UNIQUE` (`species_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `MoOSe`.`sample`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MoOSe`.`sample` (
  `sample_id` INT(11) NOT NULL AUTO_INCREMENT,
  `sample_name` VARCHAR(255) NOT NULL,
  `sample_alias` VARCHAR(255) NULL DEFAULT NULL,
  `sample_bar_code` VARCHAR(45) NULL DEFAULT NULL,
  `species_id` INT(11) NOT NULL,
  `project_id` INT(11) NOT NULL,
  `run_id` INT(11) NOT NULL,
  `application_type_id` INT(11) NOT NULL,
  PRIMARY KEY (`sample_id`),
  INDEX `fk_sample_species1_idx` (`species_id` ASC),
  INDEX `fk_sample_project1_idx` (`project_id` ASC),
  INDEX `fk_sample_run1_idx` (`run_id` ASC),
  INDEX `fk_sample_application_type1_idx` (`application_type_id` ASC),
  CONSTRAINT `fk_sample_application_type1`
    FOREIGN KEY (`application_type_id`)
    REFERENCES `MoOSe`.`application_type` (`application_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sample_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `MoOSe`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sample_run1`
    FOREIGN KEY (`run_id`)
    REFERENCES `MoOSe`.`run` (`run_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sample_species1`
    FOREIGN KEY (`species_id`)
    REFERENCES `MoOSe`.`species` (`species_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `MoOSe`.`qc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MoOSe`.`qc` (
  `qc_id` INT(11) NOT NULL AUTO_INCREMENT,
  `qc_number_of_reads` INT(11) NULL DEFAULT NULL,
  `qc_alignment_rate` DOUBLE NULL DEFAULT NULL,
  `qc_pcr_duplicates` INT(11) NULL DEFAULT NULL,
  `qc_mean_depth` DOUBLE NULL DEFAULT NULL,
  `qc_NSC_values` DOUBLE NULL DEFAULT NULL,
  `qc_RSC_values` DOUBLE NULL DEFAULT NULL,
  `qc_coverage_10_reads` DOUBLE NULL DEFAULT NULL,
  `sample_id` INT(11) NOT NULL,
  PRIMARY KEY (`qc_id`),
  INDEX `fk_qc_sample1_idx` (`sample_id` ASC),
  CONSTRAINT `fk_qc_sample1`
    FOREIGN KEY (`sample_id`)
    REFERENCES `MoOSe`.`sample` (`sample_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

------ insert into config tables


INSERT INTO `MoOSe`.`application_type` (`application_type_name`, `application_type_pattern`) VALUES ('WES', 'exome');
INSERT INTO `MoOSe`.`application_type` (`application_type_name`, `application_type_pattern`) VALUES ('WGS', 'whole genome');
INSERT INTO `MoOSe`.`application_type` (`application_type_name`, `application_type_pattern`) VALUES ('RNAseq', 'RNAseq');
INSERT INTO `MoOSe`.`application_type` (`application_type_name`, `application_type_pattern`) VALUES ('CHIPseq', 'CHIPseq');
INSERT INTO `MoOSe`.`application_type` (`application_type_name`, `application_type_pattern`) VALUES ('UNKNOWN', '******');

INSERT INTO `MoOSe`.`platform` (`platform_name`, `platform_path`) VALUES ('Nova', '/mnt/seq1/Nova');

INSERT INTO `MoOSe`.`species` (`species_name`, `species_pattern`) VALUES ('human', 'human');
INSERT INTO `MoOSe`.`species` (`species_name`, `species_pattern`) VALUES ('rat', 'rat');
INSERT INTO `MoOSe`.`species` (`species_name`, `species_pattern`) VALUES ('mouse', 'mouse');
INSERT INTO `MoOSe`.`species` (`species_name`, `species_pattern`) VALUES ('UNKNOWN', '******');

-------------- CHANGE and ADD COLUMN

ALTER TABLE `MoOSe`.`run` 
ADD COLUMN `run_comment` VARCHAR(1000) NULL AFTER `run_sample_sheet_isvalid`,
ADD COLUMN `run_index_length` VARCHAR(255) NULL AFTER `run_comment`;
ALTER TABLE `MoOSe`.`sample` 
ADD COLUMN `sample_barcode_id` INT(11) NULL AFTER `application_type_id`;

ALTER TABLE `MoOSe`.`sample` 
ADD COLUMN `sample_description` VARCHAR(255) NULL AFTER `sample_barcode_id`;

ALTER TABLE `MoOSe`.`qc` 
ADD UNIQUE INDEX `sample_id_UNIQUE` (`sample_id` ASC);

ALTER TABLE `MoOSe`.`sample` 
ADD COLUMN `sample_bar_code_source` VARCHAR(255) NULL AFTER `sample_description`;





